<?php
echo '';
echo '<div class="row">';
echo '<div class="col-sm-6">';
echo '<div class="panel panel-default" id="panel1" onmouseover="panelOn(this.id)" onmouseout="panelOff(this.id)">';
echo '<div class="panel-heading">Work Study Job Schedule</div>';
echo '<div class="panel-body">';
echo '<table class="table">';
echo '<tbody>';
echo '<tr>';
echo '<td>Monday</td>';
echo '<td>10:00AM-10:50AM</td></tr>';
echo '<tr>';
echo '<td>Tuesday</td>';
echo '<td>11:30AM-12:30PM</td></tr>';
echo '<tr>';
echo '<td>Wednesday</td>';
echo '<td>1:00PM-2:15PM</td></tr>';
echo '<tr>';
echo '<td>Thursaday</td>';
echo '<td>4:00PM-5:00PM</td></tr>';
echo '<tr>';
echo '<td>Friday</td>';
echo '<td>4:00PM-5:00PM</td></tr>';
echo '</tbody>';
echo '</table></div></div></div>';
echo '';
echo '<div class="col-sm-6">';
echo '<div class="panel panel-default" id="panel2" onmouseover="panelOn(this.id)" onmouseout="panelOff(this.id)">';
echo '<div class="panel-heading">Work Study Job Schedule</div>';
echo '<div class="panel-body">';
echo '<table class="table">';
echo '';
echo '<tbody>';
echo '<tr>';
echo '<td>Monday</td>';
echo '<td>10:00AM-10:50AM</td></tr>';
echo '<tr>';
echo '<td>Tuesday</td>';
echo '<td>11:30AM-12:30PM</td></tr>';
echo '<tr>';
echo '<td>Wednesday</td>';
echo '<td>1:00PM-2:15PM</td></tr>';
echo '<tr>';
echo '<td>Thursaday</td>';
echo '<td>4:00PM-5:00PM</td></tr>';
echo '<tr>';
echo '<td>Friday</td>';
echo '<td>4:00PM-5:00PM</td></tr>';
echo '</tbody>';
echo '</table></div></div></div></div>';
echo '';
echo '<div class="row">';
echo '<div class="col-sm-12">';
echo '<div class="panel panel-default" id="panel3" onmouseover="panelOn(this.id)" onmouseout="panelOff(this.id)">';
echo '<div class="panel-heading">Work Experiences</div>';
echo '<div class="panel-body">';
echo '<b>UTSA VP Office</b> Student Assistant; San Antonio, TX <div class="text-right">January 2019- Present</div>';
echo '<ul>';
echo '<li>First point of contact for all inquiries, and mailed in donation to the Vice President Office</li>';
echo '<li>Liaison communication between the Vice president of external relations and potential donors.';
echo 'Documented all donations using Excel and other Microsoft programs.</li>';
echo '</ul>';
echo '';
echo '<b>UTSA CS Department</b> UnderGraduate Researcher; San Antonio, Texas <div class="text-right"> August 2021- Present</div>';
echo '<ul>';
echo '<li>Collaborated with a team of 3 to create an augmented reality game.</li>';
echo '<li>Developed the game using Unity and Google AR core software.</li>';
echo '</ul>';
echo '';
echo '<b>Youth Code Fellowship Program </b> Fellow; San Antonio, Texas <div class="text-right">August 2017- May 2018</div>';
echo '<ul>';
echo '<li>Taught programming and robotics skills to 20 elementary kids</li>';
echo '<li>Collaborated with John Glenn ISD teachers to create programming lesson plans</li>';
echo '<li>Wrote 3 proposals to obtain grants to fund program</li>';
echo '</ul>';
echo '';
echo '</div></div></div></div>';
echo '<div class="row">';
echo '<div class="panel-footer">';
echo '<div class="text-center">Assignment 15 PHP</div></div>';
echo '</div>';
echo '</body>';
echo '</html>';
?>